# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tasktracker-frontend-123

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8a19cb9a73f040eab4f485a1a540ea3e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a9f8a923c2034a0eb628099e9e0ba6d5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8a19cb9a73f040eab4f485a1a540ea3e }}/spiral9memory/tasktracker_frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tasktracker-frontend-123'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b8f13a324ed642aabcb21a57eef1c610 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8a19cb9a73f040eab4f485a1a540ea3e }}/spiral9memory/tasktracker_frontend:${{ github.sha }}'